### ISSUE TITLE
Using the image for Pyhton app

### ISSUE THREAD

**Issue by kolian1** [tgagor/docker-jpegtran#1]
Hi,
I planned to use this image for Python app, but had issue installing pip3 on it.
For some reason my **docker file**:

  FROM tgagor/jpegtran:latest
  
  RUN \
      apt-get update -qq && \
      apt-get install -qq -y python3-pip && \
      apt-get install -qq -y python3 && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/*
  
  RUN pip3 install --upgrade pip3
  RUN pip3 install -U pip3 setuptools wheel

**The following error obsevred**:
Sending build context to Docker daemon  1.791MB
Step 1/12 : FROM tgagor/jpegtran:latest
 ---> c89fb71497c1
Step 3/12 : RUN     apt-get update -qq &&     apt-get install -qq -y python3-pip &&     apt-get install -qq -y python3 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 20f3ae2e82e3
Step 4/12 : RUN pip3 install -U pip3 setuptools wheel
 ---> Running in 7bda37f6b64f
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip3
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/pip3/

I do not understand what seems to be the problem.
Thanks,
 Nikolay

**Comment by tgagor** [comment]
Hi,

This image I use somewhere for image optimization. It's typical Debian image with just one package installed: `libjpeg-turbo-progs`. From this perspective I will recommend you to use `python` docker image and eventually install `jpegtran` as it will be much easier than going other way.

Support for python installation in context of this image is completely out of scope.

Good luck,
Tomasz.

**Comment by kolian1** [comment]
> Hi,
> 
> This image I use somewhere for image optimization. It's typical Debian image with just one package installed: `libjpeg-turbo-progs`. From this perspective I will recommend you to use `python` docker image and eventually install `jpegtran` as it will be much easier than going other way.
> 
> Support for python installation in context of this image is completely out of scope.
> 
> Good luck,
> Tomasz.

Hi Tomasz.
Thanks for your reply.
Actually the issue was related to requirements for jpegtran. 
While libjpeg8 and libjpeg-turbo are required: https://jpegtran-cffi.readthedocs.io/en/latest/#requirements
What actually works is: 
   libturbojpeg0-dev for pyhton3, 
   libjpeg-dev for python2.7
Now I am all set.
Hope it help anyone else.
Thanks!
